<a href="https://colab.research.google.com/github/Mohandoss20k/Data_Scraper-/blob/main/Data_Scraper_Cargos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df=pd.read_excel("justdial_Cargos.xlsx")

In [4]:
df

,Company_Name,Rating,Location,Amenities_1,Amenities_2,Phone_Number,Amenities_3,Website
0,L K Enterprises,4.5,Chennai,Parcel Booking Services,Domestic Courier Services,08460441957,NaN,https://www.justdial.com/Chennai/L-K-Enterpris...
1,Yestee Agency,4.1,Chennai,Domestic Courier,Cargo Service,08197305459,Industrial Machinery Relocation,https://www.justdial.com/Chennai/Yestee-Agency...
2,DESKMATE GLOBAL EXPRESS INDIA PRIVATE LIMITED,4.0,Chennai,Corporate Courier,Domestic Courier,08460443509,Ecommerce Courier,https://www.justdial.com/Chennai/DESKMATE-GLOB...
3,DTDC Express Limited,4.1,Chennai,Domestic Courier,Online Delivery,08460245016,Cargo Shipping,https://www.justdial.com/Chennai/DTDC-Express-...
4,Ellaam Express,4.9,Chennai,Courier Services,Parcel Booking Services,08460526690,NaN,https://www.justdial.com/Chennai/Ellaam-Expres...
...,...,...,...,...,...,...,...,...
77,Rose Cargo & Logistics Service,4.0,Udaipur-Rajasthan,Transporters For Ahmedabad,Transporters,08401024471,NaN,https://www.justdial.com/Udaipur-Rajasthan/Ros...
78,Safexpress Private Limited,3.9,Gurgaon,Cargo Service,NaN,08105143245,NaN,https://www.justdial.com/Gurgaon/Safexpress-Pr...
79,Galaxy Abroad Packers,5.0,Chennai,Domestic Courier,Cargo Service,Show Number,Pets Transportation,https://www.justdial.com/Chennai/Galaxy-Abroad...
80,Alliance Freight Express Pvt Ltd,4.4,Chennai,Cargo Service,NaN,09035032823,NaN,https://www.justdial.com/Chennai/Alliance-Frei...
81,Aps Cargo Movers,3.8,Chennai,Bulk Courier,Commercial Courier,Show Number,Corporate Courier,https://www.justdial.com/Chennai/Aps-Cargo-Mov...

In [5]:
df.shape

(82, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Company_Name  82 non-null     object
 1   Rating        82 non-null     float64
 2   Location      82 non-null     object
 3   Amenities_1   80 non-null     object
 4   Amenities_2   61 non-null     object
 5   Phone_Number  82 non-null     object
 6   Amenities_3   27 non-null     object
 7   Website       82 non-null     object
dtypes: float64(1), object(7)
memory usage: 5.3+ KB

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
print(df.columns.tolist())

['Company_Name', 'Rating ', 'Location', 'Amenities_1', 'Amenities_2', 'Phone_Number', 'Amenities_3', 'Website']

In [17]:
print(df["Phone_Number"].head())
print(df["Phone_Number"].info())

0    8460441957
1    8197305459
2    8460443509
3    8460245016
4    8460526690
Name: Phone_Number, dtype: Int64
<class 'pandas.core.series.Series'>
RangeIndex: 82 entries, 0 to 81
Series name: Phone_Number
Non-Null Count  Dtype
--------------  -----
76 non-null     Int64
dtypes: Int64(1)
memory usage: 870.0 bytes
None

In [16]:
df["Phone_Number"] = pd.to_numeric(
    df["Phone_Number"],
    errors="coerce"
).astype("Int64")

print(df["Phone_Number"].dtype)

Int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
print("Duplicate company names:",
      int(df.duplicated(subset=["Company_Name"]).sum()))

Duplicate company names: 0

In [24]:
df["Amenities"] = (
    df[["Amenities_1", "Amenities_2", "Amenities_3"]]
    .fillna("")
    .astype(str)
    .apply(
        lambda row: ",".join(
            value.strip() for value in row if value.strip()
        ),
        axis=1
    )
)

In [27]:
display(df[["Amenities_1", "Amenities_2", "Amenities_3" ,"Amenities"]].head())

,Amenities_1,Amenities_2,Amenities_3,Amenities
0,Parcel Booking Services,Domestic Courier Services,NaN,"Parcel Booking Services,Domestic Courier Services"
1,Domestic Courier,Cargo Service,Industrial Machinery Relocation,"Domestic Courier,Cargo Service,Industrial Mach..."
2,Corporate Courier,Domestic Courier,Ecommerce Courier,"Corporate Courier,Domestic Courier,Ecommerce C..."
3,Domestic Courier,Online Delivery,Cargo Shipping,"Domestic Courier,Online Delivery,Cargo Shipping"
4,Courier Services,Parcel Booking Services,NaN,"Courier Services,Parcel Booking Services"

In [28]:
df=df.drop(columns=["Amenities_1", "Amenities_2", "Amenities_3"])

In [29]:
df.head()

,Company_Name,Rating,Location,Phone_Number,Website,Amenities
0,L K Enterprises,4.5,Chennai,8460441957,https://www.justdial.com/Chennai/L-K-Enterpris...,"Parcel Booking Services,Domestic Courier Services"
1,Yestee Agency,4.1,Chennai,8197305459,https://www.justdial.com/Chennai/Yestee-Agency...,"Domestic Courier,Cargo Service,Industrial Mach..."
2,DESKMATE GLOBAL EXPRESS INDIA PRIVATE LIMITED,4.0,Chennai,8460443509,https://www.justdial.com/Chennai/DESKMATE-GLOB...,"Corporate Courier,Domestic Courier,Ecommerce C..."
3,DTDC Express Limited,4.1,Chennai,8460245016,https://www.justdial.com/Chennai/DTDC-Express-...,"Domestic Courier,Online Delivery,Cargo Shipping"
4,Ellaam Express,4.9,Chennai,8460526690,https://www.justdial.com/Chennai/Ellaam-Expres...,"Courier Services,Parcel Booking Services"

In [30]:
df["Amenities"].isnull().sum()

np.int64(0)

In [36]:
print(df["Phone_Number"].isnull().sum())

0

In [35]:
df = df.dropna(subset=["Phone_Number"])

In [31]:
# ==== Clean Location safely ====
def extract_location(location):
    if pd.isna(location):
        return None

    location = str(location).strip()
    return location if location else None

df["Location"] = df["Location"].apply(extract_location)

# ==== Clean and standardize ====
df["Location"] = (
    df["Location"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .str.title()
)

# ==== Group by Location and count records ====
location_counts = (
    df.groupby("Location")
    .size()
    .reset_index(name="Total_Records")
)

# ==== Sort by total records (descending) ====
location_counts = location_counts.sort_values(
    by="Total_Records",
    ascending=False
)

# ==== Show result ====
print(location_counts)

             Location  Total_Records
5             Chennai             25
7               Delhi              8
1           Ahmedabad              5
3           Bangalore              4
6          Coimbatore              3
9           Ernakulam              3
28            Tirupur              3
17            Kolkata              3
11            Gurgaon              2
24               Pune              2
10          Faridabad              2
4              Bhopal              2
12             Howrah              1
2    Aurangabad-Bihar              1
0                Agra              1
8             Dharwad              1
15              Jammu              1
14             Indore              1
13          Hyderabad              1
16              Kochi              1
20           Ludhiana              1
21              Morbi              1
18         Leh Ladakh              1
19            Lucknow              1
23           Namakkal              1
22             Mundra              1
26          Srirangam              1
25          Sivaganga              1
27        Thoothukudi              1
29             Trichy              1
30  Udaipur-Rajasthan              1
31           Vadodara              1

In [37]:
# ====== Enter any location ======
target_location = input("Enter location (e.g., Chennai, Coimbatore, Trichy): ").strip()

# ====== Filter data ======
filtered_df = df[
    df["Location"].astype("string").str.contains(
        target_location,
        case=False,
        na=False,
        regex=False
    )
]

# ====== Save filtered data to Excel ======
output_file = f"{target_location}_Cargos_Companies.xlsx"
filtered_df.to_excel(output_file, index=False)

# ====== Display results ======
print(f"File created: {output_file}")
print(f"Total records found: {len(filtered_df)}")

from google.colab import files
files.download(output_file)

Enter location (e.g., Chennai, Coimbatore, Trichy): chennai
File created: chennai_Cargos_Companies.xlsx
Total records found: 23

In [50]:
# Step 1: Get input from the user
location = input("Enter location: ").strip()
amenities = input("Enter amenities: ").strip()

# Step 2: Filter the dataset
filtered_df = df[
    df["Location"].str.contains(
        location, case=False, na=False, regex=False
    ) &
    df["Amenities"].str.contains(
        amenities, case=False, na=False, regex=False
    )
]

# Step 3: Display results
print("Total records found:", len(filtered_df))
display(filtered_df)

# Step 4: Save as Excel
output_file = f"{location}_{amenities}_Companies.xlsx"
filtered_df.to_excel(output_file, index=False)

# Step 5: Download the file
files.download(output_file)

Enter location: Coimbatore
Enter amenities: cargo service
Total records found: 2

,Company_Name,Rating,Location,Phone_Number,Website,Amenities,Company_Link
27,Boxmile,3.7,Coimbatore,8123855217,https://www.justdial.com/Coimbatore/Boxmile-Rg...,Cargo Service,https://BOXMILE/
28,Trailblaze Supply Chain LLP,4.1,Coimbatore,8792488466,https://www.justdial.com/Coimbatore/Trailblaze...,"Cargo Handling,Cargo Service,Cargo Service For...",https://TRAILBLAZE-SUPPLY-CHAIN-LLP/

In [42]:
import pandas as pd
import re


def create_company_link(name):
    if pd.isna(name):
        return ""

    # Replace spaces and special characters with hyphens
    name = str(name).strip().upper()
    name = re.sub(r'[^A-Z0-9]+', '-', name)
    name = name.strip('-')

    return f"https://{name}/"

# Change Company_Name to your actual company name column
df["Company_Link"] = df["Company_Name"].apply(create_company_link)

display(df[["Company_Name", "Company_Link"]].head(10))

,Company_Name,Company_Link
0,L K Enterprises,https://L-K-ENTERPRISES/
1,Yestee Agency,https://YESTEE-AGENCY/
2,DESKMATE GLOBAL EXPRESS INDIA PRIVATE LIMITED,https://DESKMATE-GLOBAL-EXPRESS-INDIA-PRIVATE-...
3,DTDC Express Limited,https://DTDC-EXPRESS-LIMITED/
4,Ellaam Express,https://ELLAAM-EXPRESS/
5,Anand Agencies Franch Express Courier Pvt Ltd,https://ANAND-AGENCIES-FRANCH-EXPRESS-COURIER-...
6,DTDC Express Ltd,https://DTDC-EXPRESS-LTD/
7,Trikaal Carriers,https://TRIKAAL-CARRIERS/
8,Sp Cargo,https://SP-CARGO/
9,Labyrinth Logistics Pvt Ltd,https://LABYRINTH-LOGISTICS-PVT-LTD/

In [43]:
df.head(10)

,Company_Name,Rating,Location,Phone_Number,Website,Amenities,Company_Link
0,L K Enterprises,4.5,Chennai,8460441957,https://www.justdial.com/Chennai/L-K-Enterpris...,"Parcel Booking Services,Domestic Courier Services",https://L-K-ENTERPRISES/
1,Yestee Agency,4.1,Chennai,8197305459,https://www.justdial.com/Chennai/Yestee-Agency...,"Domestic Courier,Cargo Service,Industrial Mach...",https://YESTEE-AGENCY/
2,DESKMATE GLOBAL EXPRESS INDIA PRIVATE LIMITED,4.0,Chennai,8460443509,https://www.justdial.com/Chennai/DESKMATE-GLOB...,"Corporate Courier,Domestic Courier,Ecommerce C...",https://DESKMATE-GLOBAL-EXPRESS-INDIA-PRIVATE-...
3,DTDC Express Limited,4.1,Chennai,8460245016,https://www.justdial.com/Chennai/DTDC-Express-...,"Domestic Courier,Online Delivery,Cargo Shipping",https://DTDC-EXPRESS-LIMITED/
4,Ellaam Express,4.9,Chennai,8460526690,https://www.justdial.com/Chennai/Ellaam-Expres...,"Courier Services,Parcel Booking Services",https://ELLAAM-EXPRESS/
5,Anand Agencies Franch Express Courier Pvt Ltd,4.5,Chennai,9054036451,https://www.justdial.com/Chennai/Anand-Agencie...,"Domestic Courier,Cargo Service,International F...",https://ANAND-AGENCIES-FRANCH-EXPRESS-COURIER-...
6,DTDC Express Ltd,4.0,Chennai,8296558430,https://www.justdial.com/Chennai/DTDC-Express-...,"24 Hours Courier Services,Courier Services",https://DTDC-EXPRESS-LTD/
7,Trikaal Carriers,4.2,Chennai,7041574889,https://www.justdial.com/Chennai/Trikaal-Carri...,"Courier Services,Transporters",https://TRIKAAL-CARRIERS/
8,Sp Cargo,4.1,Chennai,7411844120,https://www.justdial.com/Chennai/Sp-Cargo-Near...,"Commercial Courier,Corporate Courier,Ecommerce...",https://SP-CARGO/
9,Labyrinth Logistics Pvt Ltd,4.4,Chennai,9724667636,https://www.justdial.com/Chennai/Labyrinth-Log...,Cargo Service,https://LABYRINTH-LOGISTICS-PVT-LTD/

In [47]:
df.rename(columns={
    "Company_Link": "Website_Link"

})

,Company_Name,Rating,Location,Phone_Number,Website,Amenities,Website_Link
0,L K Enterprises,4.5,Chennai,8460441957,https://www.justdial.com/Chennai/L-K-Enterpris...,"Parcel Booking Services,Domestic Courier Services",https://L-K-ENTERPRISES/
1,Yestee Agency,4.1,Chennai,8197305459,https://www.justdial.com/Chennai/Yestee-Agency...,"Domestic Courier,Cargo Service,Industrial Mach...",https://YESTEE-AGENCY/
2,DESKMATE GLOBAL EXPRESS INDIA PRIVATE LIMITED,4.0,Chennai,8460443509,https://www.justdial.com/Chennai/DESKMATE-GLOB...,"Corporate Courier,Domestic Courier,Ecommerce C...",https://DESKMATE-GLOBAL-EXPRESS-INDIA-PRIVATE-...
3,DTDC Express Limited,4.1,Chennai,8460245016,https://www.justdial.com/Chennai/DTDC-Express-...,"Domestic Courier,Online Delivery,Cargo Shipping",https://DTDC-EXPRESS-LIMITED/
4,Ellaam Express,4.9,Chennai,8460526690,https://www.justdial.com/Chennai/Ellaam-Expres...,"Courier Services,Parcel Booking Services",https://ELLAAM-EXPRESS/
...,...,...,...,...,...,...,...
74,Mehala Transport,4.0,Tirupur,7487882230,https://www.justdial.com/Tirupur/Mehala-Transp...,"All India,Trucks On Rent,Cargo Service",https://MEHALA-TRANSPORT/
76,Urbx Worldwide,4.8,Ernakulam,8401097476,https://www.justdial.com/Ernakulam/Urbx-Worldw...,"Domestic Courier,Cargo Service,Warehousing",https://URBX-WORLDWIDE/
77,Rose Cargo & Logistics Service,4.0,Udaipur-Rajasthan,8401024471,https://www.justdial.com/Udaipur-Rajasthan/Ros...,"Transporters For Ahmedabad,Transporters",https://ROSE-CARGO-LOGISTICS-SERVICE/
78,Safexpress Private Limited,3.9,Gurgaon,8105143245,https://www.justdial.com/Gurgaon/Safexpress-Pr...,Cargo Service,https://SAFEXPRESS-PRIVATE-LIMITED/
80,Alliance Freight Express Pvt Ltd,4.4,Chennai,9035032823,https://www.justdial.com/Chennai/Alliance-Frei...,Cargo Service,https://ALLIANCE-FREIGHT-EXPRESS-PVT-LTD/

In [48]:
df.drop(columns=["Website"])

,Company_Name,Rating,Location,Phone_Number,Amenities,Company_Link
0,L K Enterprises,4.5,Chennai,8460441957,"Parcel Booking Services,Domestic Courier Services",https://L-K-ENTERPRISES/
1,Yestee Agency,4.1,Chennai,8197305459,"Domestic Courier,Cargo Service,Industrial Mach...",https://YESTEE-AGENCY/
2,DESKMATE GLOBAL EXPRESS INDIA PRIVATE LIMITED,4.0,Chennai,8460443509,"Corporate Courier,Domestic Courier,Ecommerce C...",https://DESKMATE-GLOBAL-EXPRESS-INDIA-PRIVATE-...
3,DTDC Express Limited,4.1,Chennai,8460245016,"Domestic Courier,Online Delivery,Cargo Shipping",https://DTDC-EXPRESS-LIMITED/
4,Ellaam Express,4.9,Chennai,8460526690,"Courier Services,Parcel Booking Services",https://ELLAAM-EXPRESS/
...,...,...,...,...,...,...
74,Mehala Transport,4.0,Tirupur,7487882230,"All India,Trucks On Rent,Cargo Service",https://MEHALA-TRANSPORT/
76,Urbx Worldwide,4.8,Ernakulam,8401097476,"Domestic Courier,Cargo Service,Warehousing",https://URBX-WORLDWIDE/
77,Rose Cargo & Logistics Service,4.0,Udaipur-Rajasthan,8401024471,"Transporters For Ahmedabad,Transporters",https://ROSE-CARGO-LOGISTICS-SERVICE/
78,Safexpress Private Limited,3.9,Gurgaon,8105143245,Cargo Service,https://SAFEXPRESS-PRIVATE-LIMITED/
80,Alliance Freight Express Pvt Ltd,4.4,Chennai,9035032823,Cargo Service,https://ALLIANCE-FREIGHT-EXPRESS-PVT-LTD/

,Company_Name,Rating,Location,Phone_Number,Website,Amenities,Website_Link
0,L K Enterprises,4.5,Chennai,8460441957,https://www.justdial.com/Chennai/L-K-Enterpris...,"Parcel Booking Services,Domestic Courier Services",https://L-K-ENTERPRISES/
1,Yestee Agency,4.1,Chennai,8197305459,https://www.justdial.com/Chennai/Yestee-Agency...,"Domestic Courier,Cargo Service,Industrial Mach...",https://YESTEE-AGENCY/
2,DESKMATE GLOBAL EXPRESS INDIA PRIVATE LIMITED,4.0,Chennai,8460443509,https://www.justdial.com/Chennai/DESKMATE-GLOB...,"Corporate Courier,Domestic Courier,Ecommerce C...",https://DESKMATE-GLOBAL-EXPRESS-INDIA-PRIVATE-...
3,DTDC Express Limited,4.1,Chennai,8460245016,https://www.justdial.com/Chennai/DTDC-Express-...,"Domestic Courier,Online Delivery,Cargo Shipping",https://DTDC-EXPRESS-LIMITED/
4,Ellaam Express,4.9,Chennai,8460526690,https://www.justdial.com/Chennai/Ellaam-Expres...,"Courier Services,Parcel Booking Services",https://ELLAAM-EXPRESS/
...,...,...,...,...,...,...,...
74,Mehala Transport,4.0,Tirupur,7487882230,https://www.justdial.com/Tirupur/Mehala-Transp...,"All India,Trucks On Rent,Cargo Service",https://MEHALA-TRANSPORT/
76,Urbx Worldwide,4.8,Ernakulam,8401097476,https://www.justdial.com/Ernakulam/Urbx-Worldw...,"Domestic Courier,Cargo Service,Warehousing",https://URBX-WORLDWIDE/
77,Rose Cargo & Logistics Service,4.0,Udaipur-Rajasthan,8401024471,https://www.justdial.com/Udaipur-Rajasthan/Ros...,"Transporters For Ahmedabad,Transporters",https://ROSE-CARGO-LOGISTICS-SERVICE/
78,Safexpress Private Limited,3.9,Gurgaon,8105143245,https://www.justdial.com/Gurgaon/Safexpress-Pr...,Cargo Service,https://SAFEXPRESS-PRIVATE-LIMITED/
80,Alliance Freight Express Pvt Ltd,4.4,Chennai,9035032823,https://www.justdial.com/Chennai/Alliance-Frei...,Cargo Service,https://ALLIANCE-FREIGHT-EXPRESS-PVT-LTD/