<a href="https://colab.research.google.com/github/Mohandoss20k/Data_Scraper-/blob/main/Data_Scraper_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_excel("justdial.logistic.xlsx")

In [ ]:
df

,Company_Name,Rating,Review_Rating,locatcity,Service_Start,Amenities_1,Phone_Number,Verification,Amenities_2,Amenities_3,Website
0,Seu Worldwide Logistics Pvt Ltd,5.0,4 Ratings,Chennai,5 Years,Door to Door,9.725386e+09,NaN,NaN,NaN,https://www.justdial.com/Chennai/Seu-Worldwide...
1,Uni Logistic Agencies Pvt Ltd,4.7,40 Ratings,Chennai,24 Years,Delivery Available,7.041499e+09,verified by Justdial.,NaN,NaN,https://www.justdial.com/Chennai/Uni-Logistic-...
2,Rapiditors Logistics,4.2,49 Ratings,Chennai,3 Years,Domestic Courier,7.041644e+09,verified by Justdial.,Cargo Service,All India,https://www.justdial.com/Chennai/Rapiditors-Lo...
3,Shri Ramajayam Freight Logistics,4.0,88 Ratings,Chennai,48 Years,Cargo Service,9.972805e+09,verified by Justdial.,NaN,NaN,https://www.justdial.com/Chennai/Shri-Ramajaya...
4,St Courier,3.7,191 Ratings,Chennai,40 Years,Cargo Service,9.731862e+09,NaN,Domestic Courier,Bulk Courier,https://www.justdial.com/Chennai/St-Courier-Ne...
...,...,...,...,...,...,...,...,...,...,...,...
158,Fastmove Courier & Cargo Services,4.0,14 Ratings,Pune,7 Years,Door to Door,7.041652e+09,NaN,NaN,NaN,https://www.justdial.com/Pune/Fastmove-Courier...
159,One Source Logistics Pvt Ltd,3.8,69 Ratings,Navi Mumbai,19 Years,Domestic Courier,7.411651e+09,NaN,NaN,NaN,https://www.justdial.com/Navi-Mumbai/One-Sourc...
160,Pace Roadways Pvt Ltd,4.1,218 Ratings,Indore,22 Years,Domestic Courier,8.904891e+09,verified by Justdial.,Trucks On Rent,Cargo Service,https://www.justdial.com/Indore/Pace-Roadways-...
161,Friendship Organization,3.6,12 Ratings,Jajpur,4 Years,Transporters,9.036643e+09,NaN,Logistic Services,NaN,https://www.justdial.com/Jajpur/Friendship-Org...
162,Welcome Logistics,4.3,38 Ratings,Indore,7 Years,Transporters,7.487913e+09,verified by Justdial.,Packers And Movers,NaN,https://www.justdial.com/Indore/Welcome-Logist...

In [ ]:
df.shape

(163, 11)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company_Name   157 non-null    object
 1   Rating         157 non-null    float64
 2   Review_Rating  157 non-null    object
 3   locatcity      157 non-null    object
 4   Service_Start  151 non-null    object
 5   Amenities_1    155 non-null    object
 6   Phone_Number   154 non-null    float64
 7   Verification   61 non-null     object
 8   Amenities_2    106 non-null    object
 9   Amenities_3    64 non-null     object
 10  Website        157 non-null    object
dtypes: float64(2), object(9)
memory usage: 14.1+ KB

In [ ]:
df.duplicated().sum()

np.int64(72)

In [ ]:
print(df.columns.tolist())

['Company_Name', 'Rating', 'Review_Rating', 'locatcity', 'Service_Start', 'Amenities_1', 'Phone_Number ', 'Verification', 'Amenities_2', 'Amenities_3', 'Website ']

In [ ]:
df.columns = df.columns.str.strip()

print(df.columns.tolist())

['Company_Name', 'Rating', 'Review_Rating', 'locatcity', 'Service_Start', 'Amenities_1', 'Phone_Number', 'Verification', 'Amenities_2', 'Amenities_3', 'Website']

In [ ]:
print(df["Phone_Number"].head())
print(df["Phone_Number"].dtype)

0    9.725386e+09
1    7.041499e+09
2    7.041644e+09
3    9.972805e+09
4    9.731862e+09
Name: Phone_Number, dtype: float64
float64

In [ ]:
import pandas as pd

# Convert scientific notation to digit strings
df["Phone_Number"] = df["Phone_Number"].apply(
    lambda x: str(int(x)) if pd.notna(x) else ""
)

# Display the result
print(df["Phone_Number"].head(10))

0    9725385693
1    7041499372
2    7041643819
3    9972805482
4    9731862415
5    9972838681
6    8147618411
7    8401620803
8    8460245016
9    8734947251
Name: Phone_Number, dtype: object

In [ ]:
df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)
print("Remaining duplicates:", int(df.duplicated().sum()))

Shape after removing duplicates: (91, 11)
Remaining duplicates: 0

In [ ]:
print("Duplicate company names:",
      int(df.duplicated(subset=["Company_Name"]).sum()))

Duplicate company names: 12

In [ ]:
df = df.drop_duplicates(subset=["Company_Name"], keep="first")

In [ ]:
df.shape

(79, 11)

In [ ]:
df["Amenities"] = (
    df[["Amenities_1", "Amenities_2", "Amenities_3"]]
    .fillna("")
    .astype(str)
    .apply(lambda row: ", ".join(value.strip() for value in row if value.strip()), axis=1)
)

# Display the result
display(df[["Amenities_1", "Amenities_2", "Amenities_3", "Amenities"]].head())

,Amenities_1,Amenities_2,Amenities_3,Amenities
0,Door to Door,NaN,NaN,Door to Door
1,Delivery Available,NaN,NaN,Delivery Available
2,Domestic Courier,Cargo Service,All India,"Domestic Courier, Cargo Service, All India"
3,Cargo Service,NaN,NaN,Cargo Service
4,Cargo Service,Domestic Courier,Bulk Courier,"Cargo Service, Domestic Courier, Bulk Courier"

In [ ]:
df=df.drop(columns=["Amenities_1","Amenities_2","Amenities_3"])

In [ ]:
df.head(10)

,Company_Name,Rating,Review_Rating,locatcity,Service_Start,Phone_Number,Verification,Website,Amenities
0,Seu Worldwide Logistics Pvt Ltd,5.0,4 Ratings,Chennai,5 Years,9725385693,NaN,https://www.justdial.com/Chennai/Seu-Worldwide...,Door to Door
1,Uni Logistic Agencies Pvt Ltd,4.7,40 Ratings,Chennai,24 Years,7041499372,verified by Justdial.,https://www.justdial.com/Chennai/Uni-Logistic-...,Delivery Available
2,Rapiditors Logistics,4.2,49 Ratings,Chennai,3 Years,7041643819,verified by Justdial.,https://www.justdial.com/Chennai/Rapiditors-Lo...,"Domestic Courier, Cargo Service, All India"
3,Shri Ramajayam Freight Logistics,4.0,88 Ratings,Chennai,48 Years,9972805482,verified by Justdial.,https://www.justdial.com/Chennai/Shri-Ramajaya...,Cargo Service
4,St Courier,3.7,191 Ratings,Chennai,40 Years,9731862415,NaN,https://www.justdial.com/Chennai/St-Courier-Ne...,"Cargo Service, Domestic Courier, Bulk Courier"
5,Chitra Transport,4.1,45 Ratings,Chennai,47 Years,9972838681,verified by Justdial.,https://www.justdial.com/Chennai/Chitra-Transp...,"Logistic Services, Logistic Services For Chennai"
6,GP Roadlines,3.8,17 Ratings,Chennai,9 Years,8147618411,verified by Justdial.,https://www.justdial.com/Chennai/GP-Roadlines-...,"Cargo Service, Domestic Courier"
7,Valuable Swift Courier LLP,4.3,4 Ratings,Chennai,7 Years,8401620803,NaN,https://www.justdial.com/Chennai/Valuable-Swif...,24X7 Customer Care
8,DTDC Express Limited,4.1,75 Ratings,Chennai,13 Years,8460245016,verified by Justdial.,https://www.justdial.com/Chennai/DTDC-Express-...,"Domestic Courier, Online Delivery, Cargo Shipping"
9,OMEGA EXPRESS LOGISTICS,5.0,335 Ratings,Chennai,6 Years,8734947251,NaN,https://www.justdial.com/Chennai/OMEGA-EXPRESS...,"Corporate Courier, All India, Warehousing"

In [ ]:
df["Amenities"].isnull().sum()

np.int64(0)

In [ ]:
print(df.columns.tolist())

['Company_Name', 'Rating', 'Review_Rating', 'locatcity', 'Service_Start', 'Phone_Number', 'Verification', 'Website', 'Amenities']

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
print(df.columns.tolist())

['Company_Name', 'Rating', 'Review_Rating', 'locatcity', 'Service_Start', 'Phone_Number', 'Verification', 'Website', 'Amenities']

In [ ]:
df["Short_URL"] = (
    df["Website"]
    .str.strip()
    .str.replace(r"[?#].*$", "", regex=True)
)

In [ ]:
df.head(10)

,Company_Name,Rating,Review_Rating,locatcity,Service_Start,Phone_Number,Verification,Website,Amenities,Website_Domain,Short_URL
0,Seu Worldwide Logistics Pvt Ltd,5.0,4 Ratings,Chennai,5 Years,9725385693,NaN,justdial.com,Door to Door,justdial.com,justdial.com
1,Uni Logistic Agencies Pvt Ltd,4.7,40 Ratings,Chennai,24 Years,7041499372,verified by Justdial.,justdial.com,Delivery Available,justdial.com,justdial.com
2,Rapiditors Logistics,4.2,49 Ratings,Chennai,3 Years,7041643819,verified by Justdial.,justdial.com,"Domestic Courier, Cargo Service, All India",justdial.com,justdial.com
3,Shri Ramajayam Freight Logistics,4.0,88 Ratings,Chennai,48 Years,9972805482,verified by Justdial.,justdial.com,Cargo Service,justdial.com,justdial.com
4,St Courier,3.7,191 Ratings,Chennai,40 Years,9731862415,NaN,justdial.com,"Cargo Service, Domestic Courier, Bulk Courier",justdial.com,justdial.com
5,Chitra Transport,4.1,45 Ratings,Chennai,47 Years,9972838681,verified by Justdial.,justdial.com,"Logistic Services, Logistic Services For Chennai",justdial.com,justdial.com
6,GP Roadlines,3.8,17 Ratings,Chennai,9 Years,8147618411,verified by Justdial.,justdial.com,"Cargo Service, Domestic Courier",justdial.com,justdial.com
7,Valuable Swift Courier LLP,4.3,4 Ratings,Chennai,7 Years,8401620803,NaN,justdial.com,24X7 Customer Care,justdial.com,justdial.com
8,DTDC Express Limited,4.1,75 Ratings,Chennai,13 Years,8460245016,verified by Justdial.,justdial.com,"Domestic Courier, Online Delivery, Cargo Shipping",justdial.com,justdial.com
9,OMEGA EXPRESS LOGISTICS,5.0,335 Ratings,Chennai,6 Years,8734947251,NaN,justdial.com,"Corporate Courier, All India, Warehousing",justdial.com,justdial.com

In [ ]:
df["Short_URL"] = df["Website"].apply(
    lambda url: "/" + "/".join(urlparse(str(url)).path.strip("/").split("/")[:2])
    if pd.notna(url) and urlparse(str(url)).path.strip("/")
    else ""
)

In [ ]:
display(df[["Website", "Short_URL"]].head(10))

        Website      Short_URL
0  justdial.com  /justdial.com
1  justdial.com  /justdial.com
2  justdial.com  /justdial.com
3  justdial.com  /justdial.com
4  justdial.com  /justdial.com
5  justdial.com  /justdial.com
6  justdial.com  /justdial.com
7  justdial.com  /justdial.com
8  justdial.com  /justdial.com
9  justdial.com  /justdial.com

In [ ]:
from urllib.parse import urlparse
import pandas as pd

def extract_short_url(url):
    if pd.isna(url):
        return ""

    path = urlparse(str(url)).path.strip("/")
    parts = path.split("/")

    if len(parts) >= 2:
        return "/" + "/".join(parts[:2])

    return ""

df["Short_URL"] = df["Website"].apply(extract_short_url)

In [ ]:
df.head()

,Company_Name,Rating,Review_Rating,locatcity,Service_Start,Phone_Number,Verification,Website,Amenities,Website_Domain,Short_URL
0,Seu Worldwide Logistics Pvt Ltd,5.0,4 Ratings,Chennai,5 Years,9725385693,NaN,justdial.com,Door to Door,justdial.com,
1,Uni Logistic Agencies Pvt Ltd,4.7,40 Ratings,Chennai,24 Years,7041499372,verified by Justdial.,justdial.com,Delivery Available,justdial.com,
2,Rapiditors Logistics,4.2,49 Ratings,Chennai,3 Years,7041643819,verified by Justdial.,justdial.com,"Domestic Courier, Cargo Service, All India",justdial.com,
3,Shri Ramajayam Freight Logistics,4.0,88 Ratings,Chennai,48 Years,9972805482,verified by Justdial.,justdial.com,Cargo Service,justdial.com,
4,St Courier,3.7,191 Ratings,Chennai,40 Years,9731862415,NaN,justdial.com,"Cargo Service, Domestic Courier, Bulk Courier",justdial.com,

In [ ]:
import pandas as pd
from urllib.parse import urlparse

def clean_url(url):
    if pd.isna(url):
        return ""

    url = str(url).strip()

    # Extract the URL path
    parsed = urlparse(url)

    # Remove the ID and tracking parameters, keeping company name
    parts = parsed.path.strip("/").split("/")

    if len(parts) >= 2:
        return f"{parsed.scheme}://{parsed.netloc}/{parts[0]}/{parts[1]}/"

    return url

# Replace Website with your actual Excel column name
df["Website"] = df["Website"].apply(clean_url)

print(df["Website"].head(10))

0    justdial.com
1    justdial.com
2    justdial.com
3    justdial.com
4    justdial.com
5    justdial.com
6    justdial.com
7    justdial.com
8    justdial.com
9    justdial.com
Name: Website, dtype: object

In [ ]:
display(df[["Website", "Short_URL"]].head(10))

        Website Short_URL
0  justdial.com
1  justdial.com
2  justdial.com
3  justdial.com
4  justdial.com
5  justdial.com
6  justdial.com
7  justdial.com
8  justdial.com
9  justdial.com

In [ ]:
import pandas as pd
import re

def clean_url(url):
    if pd.isna(url):
        return ""

    url = str(url).strip()

    match = re.search(
        r'https?://[^/]+/([^/?]+/[^/?]+)',
        url
    )

    if match:
        return "https://www.justdial.com/" + match.group(1).rstrip("/") + "/"

    return url

# Change Website to your actual column name
df["Website"] = df["Website"].apply(clean_url)

# Display the cleaned links without downloading
display(df[["Website"]].head(20))

         Website
0   justdial.com
1   justdial.com
2   justdial.com
3   justdial.com
4   justdial.com
5   justdial.com
6   justdial.com
7   justdial.com
8   justdial.com
9   justdial.com
10
19  justdial.com
20  justdial.com
22  justdial.com
23  justdial.com
24  justdial.com
25  justdial.com
26  justdial.com
27  justdial.com
28  justdial.com

In [ ]:
df.head(10)

,Company_Name,Rating,Review_Rating,locatcity,Service_Start,Phone_Number,Verification,Website,Amenities,Website_Domain,Short_URL
0,Seu Worldwide Logistics Pvt Ltd,5.0,4 Ratings,Chennai,5 Years,9725385693,NaN,justdial.com,Door to Door,justdial.com,
1,Uni Logistic Agencies Pvt Ltd,4.7,40 Ratings,Chennai,24 Years,7041499372,verified by Justdial.,justdial.com,Delivery Available,justdial.com,
2,Rapiditors Logistics,4.2,49 Ratings,Chennai,3 Years,7041643819,verified by Justdial.,justdial.com,"Domestic Courier, Cargo Service, All India",justdial.com,
3,Shri Ramajayam Freight Logistics,4.0,88 Ratings,Chennai,48 Years,9972805482,verified by Justdial.,justdial.com,Cargo Service,justdial.com,
4,St Courier,3.7,191 Ratings,Chennai,40 Years,9731862415,NaN,justdial.com,"Cargo Service, Domestic Courier, Bulk Courier",justdial.com,
5,Chitra Transport,4.1,45 Ratings,Chennai,47 Years,9972838681,verified by Justdial.,justdial.com,"Logistic Services, Logistic Services For Chennai",justdial.com,
6,GP Roadlines,3.8,17 Ratings,Chennai,9 Years,8147618411,verified by Justdial.,justdial.com,"Cargo Service, Domestic Courier",justdial.com,
7,Valuable Swift Courier LLP,4.3,4 Ratings,Chennai,7 Years,8401620803,NaN,justdial.com,24X7 Customer Care,justdial.com,
8,DTDC Express Limited,4.1,75 Ratings,Chennai,13 Years,8460245016,verified by Justdial.,justdial.com,"Domestic Courier, Online Delivery, Cargo Shipping",justdial.com,
9,OMEGA EXPRESS LOGISTICS,5.0,335 Ratings,Chennai,6 Years,8734947251,NaN,justdial.com,"Corporate Courier, All India, Warehousing",justdial.com,

In [ ]:
import pandas as pd
import re

def create_company_link(name):
    if pd.isna(name):
        return ""

    # Replace spaces and special characters with hyphens
    name = str(name).strip().upper()
    name = re.sub(r'[^A-Z0-9]+', '-', name)
    name = name.strip('-')

    return f"https://{name}/"

# Change Company_Name to your actual company name column
df["Company_Link"] = df["Company_Name"].apply(create_company_link)

display(df[["Company_Name", "Company_Link"]].head(10))

                       Company_Name                               Company_Link
0   Seu Worldwide Logistics Pvt Ltd   https://SEU-WORLDWIDE-LOGISTICS-PVT-LTD/
1     Uni Logistic Agencies Pvt Ltd     https://UNI-LOGISTIC-AGENCIES-PVT-LTD/
2              Rapiditors Logistics              https://RAPIDITORS-LOGISTICS/
3  Shri Ramajayam Freight Logistics  https://SHRI-RAMAJAYAM-FREIGHT-LOGISTICS/
4                        St Courier                        https://ST-COURIER/
5                  Chitra Transport                  https://CHITRA-TRANSPORT/
6                      GP Roadlines                      https://GP-ROADLINES/
7        Valuable Swift Courier LLP        https://VALUABLE-SWIFT-COURIER-LLP/
8              DTDC Express Limited              https://DTDC-EXPRESS-LIMITED/
9           OMEGA EXPRESS LOGISTICS           https://OMEGA-EXPRESS-LOGISTICS/

In [ ]:
df.head(10)

,Company_Name,Rating,Review_Rating,locatcity,Service_Start,Phone_Number,Verification,Website,Amenities,Website_Domain,Short_URL,Company_Link
0,Seu Worldwide Logistics Pvt Ltd,5.0,4 Ratings,Chennai,5 Years,9725385693,NaN,justdial.com,Door to Door,justdial.com,,https://SEU-WORLDWIDE-LOGISTICS-PVT-LTD/
1,Uni Logistic Agencies Pvt Ltd,4.7,40 Ratings,Chennai,24 Years,7041499372,verified by Justdial.,justdial.com,Delivery Available,justdial.com,,https://UNI-LOGISTIC-AGENCIES-PVT-LTD/
2,Rapiditors Logistics,4.2,49 Ratings,Chennai,3 Years,7041643819,verified by Justdial.,justdial.com,"Domestic Courier, Cargo Service, All India",justdial.com,,https://RAPIDITORS-LOGISTICS/
3,Shri Ramajayam Freight Logistics,4.0,88 Ratings,Chennai,48 Years,9972805482,verified by Justdial.,justdial.com,Cargo Service,justdial.com,,https://SHRI-RAMAJAYAM-FREIGHT-LOGISTICS/
4,St Courier,3.7,191 Ratings,Chennai,40 Years,9731862415,NaN,justdial.com,"Cargo Service, Domestic Courier, Bulk Courier",justdial.com,,https://ST-COURIER/
5,Chitra Transport,4.1,45 Ratings,Chennai,47 Years,9972838681,verified by Justdial.,justdial.com,"Logistic Services, Logistic Services For Chennai",justdial.com,,https://CHITRA-TRANSPORT/
6,GP Roadlines,3.8,17 Ratings,Chennai,9 Years,8147618411,verified by Justdial.,justdial.com,"Cargo Service, Domestic Courier",justdial.com,,https://GP-ROADLINES/
7,Valuable Swift Courier LLP,4.3,4 Ratings,Chennai,7 Years,8401620803,NaN,justdial.com,24X7 Customer Care,justdial.com,,https://VALUABLE-SWIFT-COURIER-LLP/
8,DTDC Express Limited,4.1,75 Ratings,Chennai,13 Years,8460245016,verified by Justdial.,justdial.com,"Domestic Courier, Online Delivery, Cargo Shipping",justdial.com,,https://DTDC-EXPRESS-LIMITED/
9,OMEGA EXPRESS LOGISTICS,5.0,335 Ratings,Chennai,6 Years,8734947251,NaN,justdial.com,"Corporate Courier, All India, Warehousing",justdial.com,,https://OMEGA-EXPRESS-LOGISTICS/

In [ ]:
df=df.drop(columns=["Website","Website_Domain","Short_URL"])

In [ ]:
df.head(10)

,Company_Name,Rating,Review_Rating,locatcity,Service_Start,Phone_Number,Verification,Amenities,Company_Link
0,Seu Worldwide Logistics Pvt Ltd,5.0,4 Ratings,Chennai,5 Years,9725385693,NaN,Door to Door,https://SEU-WORLDWIDE-LOGISTICS-PVT-LTD/
1,Uni Logistic Agencies Pvt Ltd,4.7,40 Ratings,Chennai,24 Years,7041499372,verified by Justdial.,Delivery Available,https://UNI-LOGISTIC-AGENCIES-PVT-LTD/
2,Rapiditors Logistics,4.2,49 Ratings,Chennai,3 Years,7041643819,verified by Justdial.,"Domestic Courier, Cargo Service, All India",https://RAPIDITORS-LOGISTICS/
3,Shri Ramajayam Freight Logistics,4.0,88 Ratings,Chennai,48 Years,9972805482,verified by Justdial.,Cargo Service,https://SHRI-RAMAJAYAM-FREIGHT-LOGISTICS/
4,St Courier,3.7,191 Ratings,Chennai,40 Years,9731862415,NaN,"Cargo Service, Domestic Courier, Bulk Courier",https://ST-COURIER/
5,Chitra Transport,4.1,45 Ratings,Chennai,47 Years,9972838681,verified by Justdial.,"Logistic Services, Logistic Services For Chennai",https://CHITRA-TRANSPORT/
6,GP Roadlines,3.8,17 Ratings,Chennai,9 Years,8147618411,verified by Justdial.,"Cargo Service, Domestic Courier",https://GP-ROADLINES/
7,Valuable Swift Courier LLP,4.3,4 Ratings,Chennai,7 Years,8401620803,NaN,24X7 Customer Care,https://VALUABLE-SWIFT-COURIER-LLP/
8,DTDC Express Limited,4.1,75 Ratings,Chennai,13 Years,8460245016,verified by Justdial.,"Domestic Courier, Online Delivery, Cargo Shipping",https://DTDC-EXPRESS-LIMITED/
9,OMEGA EXPRESS LOGISTICS,5.0,335 Ratings,Chennai,6 Years,8734947251,NaN,"Corporate Courier, All India, Warehousing",https://OMEGA-EXPRESS-LOGISTICS/

In [ ]:
df.rename(columns={
    "locatcity": "Location",
    "Company_Link": "Website Link",
    }, inplace=True)

In [ ]:
print(df.columns.tolist())

['Company_Name', 'Rating', 'Review_Rating', 'Location', 'Service_Start', 'Phone_Number', 'Verification', 'Amenities', 'Website Link']

In [ ]:
import re
import pandas as pd

# ==== Clean Location safely ====
def extract_location(location):
    if pd.isna(location):
        return None

    location = str(location).strip()
    return location if location else None

df["Location"] = df["Location"].apply(extract_location)

# ==== Clean and standardize ====
df["Location"] = (
    df["Location"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .str.title()
)

# ==== Group by Location and count records ====
location_counts = (
    df.groupby("Location")
    .size()
    .reset_index(name="Total_Records")
)

# ==== Sort by total records (descending) ====
location_counts = location_counts.sort_values(
    by="Total_Records",
    ascending=False
)

# ==== Show result ====
print(location_counts)

               Location  Total_Records
1               Chennai             36
2            Coimbatore              5
0             Bangalore              4
13               Mumbai              4
3             Ernakulam              3
16          Navi Mumbai              3
6             Hyderabad              2
7                Indore              2
8                Jajpur              1
5                 Hubli              1
4                 Hosur              1
10             Kolhapur              1
9               Jalgaon              1
12            Mangalore              1
11         Mahabubnagar              1
14               Mysore              1
15               Nashik              1
17             Palakkad              1
18           Perambalur              1
19                 Pune              1
20  Raipur-Chhattisgarh              1
21                Salem              1
22            Sivaganga              1
23            Srirangam              1
24                Thane              1
25          Thoothukudi              1
26              Tirupur              1

In [ ]:
from google.colab import files
df.to_excel("cleaned_data.xlsx", index=False)
files.download("cleaned_data.xlsx")

In [ ]:
# ====== Enter any location ======
target_location = input("Enter location (e.g., Chennai, Madurai): ").strip()

# ====== Filter data ======
filtered_df = df[
    df["Location"].astype("string").str.contains(
        target_location,
        case=False,
        na=False,
        regex=False
    )
]

# ====== Save filtered data to Excel ======
output_file = f"{target_location}_Logistics_Companies.xlsx"
filtered_df.to_excel(output_file, index=False)

# ====== Display results ======
print(f"File created: {output_file}")
print(f"Total records found: {len(filtered_df)}")

from google.colab import files
files.download(output_file)

Enter location (e.g., Chennai, Madurai): chennai
File created: chennai_Logistics_Companies.xlsx
Total records found: 36