<a href="https://colab.research.google.com/github/Mohandoss20k/Data_Scraper-/blob/main/P%26Mipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [78]:
import pandas as pd

In [79]:
df=pd.read_excel("packer_and_movers1.xlsx")

In [80]:
df

,Company_Name,Rating,location,Amenities_1,Amenities_2,Amenities_3,Phone_Number,Website
0,A 1 Trans Logistic Packers & Movers,4.0,"Thiruverkadu Road Poonamallee, Chennai",Residential Relocation,Domestic Shifting,All India,8.147128e+09,https://www.justdial.com/Chennai/A-1-Trans-Log...
1,Thangam Packers and Movers,4.4,Sri Ayyappan Nagar 1st Main Road Virugambakkam...,Budget Friendly,Warehousing,Two Wheeler Transportation,9.740218e+09,https://www.justdial.com/Chennai/Thangam-Packe...
2,Sri Thirumalai Packers Movers and Transports,4.3,"Srinivasapuram Iyyappanthangal, Chennai",Residential Relocation,NaN,NaN,8.904958e+09,https://www.justdial.com/Chennai/Sri-Thirumala...
3,Sriram Packers and Movers,4.0,"Ptk Nagar Thiruvanmiyur, Chennai",Residential Relocation,All India,NaN,9.731865e+09,https://www.justdial.com/Chennai/Sriram-Packer...
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
176,Southern Logistic Packers and Movers,4.6,"Poonamallee Bypass Road Ambal Nager, Chennai",Indian Banks Association Approved,NaN,NaN,NaN,https://www.justdial.com/Chennai/Southern-Logi...
177,Vr Logistics Packers and Movers,4.6,"Balaji Nagar Main Road Puzhal, Chennai",Packers And Movers For Bangalore,Packers And Movers,NaN,NaN,https://www.justdial.com/Chennai/Vr-Logistics-...
178,Sri Hari Packers & Movers,3.0,"Bharathi Nagar Thiruvanmiyur, Chennai",All India,NaN,NaN,NaN,https://www.justdial.com/Chennai/Sri-Hari-Pack...
179,Papathi Packers and Movers,4.8,"Kalaingar Karunanidhi Nagar K K Nagar, Chennai",All India,NaN,NaN,NaN,https://www.justdial.com/Chennai/Papathi-Packe...
180,Ashwin Transport & Packers Movers,4.2,"Mohan Nagar-Maadambakkam, Chennai",Packers And Movers,Packers And Movers (Within City),NaN,NaN,https://www.justdial.com/Chennai/Ashwin-Transp...

In [51]:
df.shape

(181, 8)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company_Name   177 non-null    object
 1   Rating         177 non-null    float64
 2   location       177 non-null    object
 3   Amenities_1    175 non-null    object
 4   Amenities_2    136 non-null    object
 5   Amenities_3    60 non-null     object
 6   Phone_Number   86 non-null     float64
 7   Website        177 non-null    object
dtypes: float64(2), object(6)
memory usage: 11.4+ KB

In [53]:
df.duplicated().sum()

np.int64(80)

In [54]:
df=df.drop_duplicates()

In [55]:
df.duplicated().sum()

np.int64(0)

In [56]:
df["Phone_Number"]=df["Phone_Number"].apply(
    lambda x : str(int(x) if pd.notna(x) else"")
)

/tmp/ipykernel_2540/3774584302.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Phone_Number"]=df["Phone_Number"].apply(

In [57]:
print(df["Phone_Number"].head(10))

0    8147127798
1    9740217991
2    8904957639
3    9731864889
4
5    8511079107
6    8511392567
7    8123746034
8    9724736220
9    8197736194
Name: Phone_Number, dtype: object

In [82]:
print(df.columns.tolist())

['Company_Name ', 'Rating', 'location', 'Amenities_1', 'Amenities_2', 'Amenities_3', 'Phone_Number', 'Website']

In [59]:
print(df["Phone_Number"].duplicated().sum())

52

In [60]:
df.shape

(101, 8)

In [83]:
df["Amenities"]=(df[["Amenities_1", "Amenities_2", "Amenities_3"]]
                 .fillna("")
                 .astype(str)
                 .apply(lambda x: ", ".join(value.strip() for value in x if value.strip()),axis=1)
                 )

In [84]:
print(df[["Amenities_1", "Amenities_2", "Amenities_3", "Amenities"]].head(10))

              Amenities_1                       Amenities_2  \
0  Residential Relocation                 Domestic Shifting
1         Budget Friendly                       Warehousing
2  Residential Relocation                               NaN
3  Residential Relocation                         All India
4                     NaN                               NaN
5  Residential Relocation                       Within City
6  Residential Relocation                       Within City
7      Packers And Movers  Packers And Movers (Within City)
8       Interstate Moving              Intercity Relocation
9  Residential Relocation                         All India

                       Amenities_3  \
0                        All India
1       Two Wheeler Transportation
2                              NaN
3                              NaN
4                              NaN
5                              NaN
6                              NaN
7                              NaN
8  Industrial Machinery Relocation
9                      Within City

                                           Amenities
0  Residential Relocation, Domestic Shifting, All...
1  Budget Friendly, Warehousing, Two Wheeler Tran...
2                             Residential Relocation
3                  Residential Relocation, All India
4
5                Residential Relocation, Within City
6                Residential Relocation, Within City
7  Packers And Movers, Packers And Movers (Within...
8  Interstate Moving, Intercity Relocation, Indus...
9     Residential Relocation, All India, Within City

In [63]:
print(df["Amenities"].isnull().sum())

0

In [85]:
df.drop(columns=["Amenities_1", "Amenities_2", "Amenities_3"], inplace=True)

In [86]:
df.head(10)

,Company_Name,Rating,location,Phone_Number,Website,Amenities
0,A 1 Trans Logistic Packers & Movers,4.0,"Thiruverkadu Road Poonamallee, Chennai",8.147128e+09,https://www.justdial.com/Chennai/A-1-Trans-Log...,"Residential Relocation, Domestic Shifting, All..."
1,Thangam Packers and Movers,4.4,Sri Ayyappan Nagar 1st Main Road Virugambakkam...,9.740218e+09,https://www.justdial.com/Chennai/Thangam-Packe...,"Budget Friendly, Warehousing, Two Wheeler Tran..."
2,Sri Thirumalai Packers Movers and Transports,4.3,"Srinivasapuram Iyyappanthangal, Chennai",8.904958e+09,https://www.justdial.com/Chennai/Sri-Thirumala...,Residential Relocation
3,Sriram Packers and Movers,4.0,"Ptk Nagar Thiruvanmiyur, Chennai",9.731865e+09,https://www.justdial.com/Chennai/Sriram-Packer...,"Residential Relocation, All India"
4,NaN,NaN,NaN,NaN,NaN,
5,Jayam Packers and Movers,3.9,"Annai Sathya Nagar 8th Street Nesapakkam, Chennai",8.511079e+09,https://www.justdial.com/Chennai/Jayam-Packers...,"Residential Relocation, Within City"
6,Royal Packers and Movers,3.3,"Sulthan Pettai Mangadu, Chennai",8.511393e+09,https://www.justdial.com/Chennai/Royal-Packers...,"Residential Relocation, Within City"
7,Superline Packers and Movers,4.7,"Near Sathyamoorthy Nagar Vyasarpadi, Chennai",8.123746e+09,https://www.justdial.com/Chennai/Superline-Pac...,"Packers And Movers, Packers And Movers (Within..."
8,Youngers Packers and Movers,4.1,"Ajantha Avenue Kottivakkam, Chennai",9.724736e+09,https://www.justdial.com/Chennai/Youngers-Pack...,"Interstate Moving, Intercity Relocation, Indus..."
9,Nathish Transport,4.3,"Indira Nagar Kolathur, Chennai",8.197736e+09,https://www.justdial.com/Chennai/Nathish-Trans...,"Residential Relocation, All India, Within City"

In [87]:
print(df.columns.tolist())

['Company_Name ', 'Rating', 'location', 'Phone_Number', 'Website', 'Amenities']

In [88]:
df.columns = df.columns.str.strip()

In [89]:
print(df.columns.tolist())

['Company_Name', 'Rating', 'location', 'Phone_Number', 'Website', 'Amenities']

In [90]:
df.head(10)

,Company_Name,Rating,location,Phone_Number,Website,Amenities
0,A 1 Trans Logistic Packers & Movers,4.0,"Thiruverkadu Road Poonamallee, Chennai",8.147128e+09,https://www.justdial.com/Chennai/A-1-Trans-Log...,"Residential Relocation, Domestic Shifting, All..."
1,Thangam Packers and Movers,4.4,Sri Ayyappan Nagar 1st Main Road Virugambakkam...,9.740218e+09,https://www.justdial.com/Chennai/Thangam-Packe...,"Budget Friendly, Warehousing, Two Wheeler Tran..."
2,Sri Thirumalai Packers Movers and Transports,4.3,"Srinivasapuram Iyyappanthangal, Chennai",8.904958e+09,https://www.justdial.com/Chennai/Sri-Thirumala...,Residential Relocation
3,Sriram Packers and Movers,4.0,"Ptk Nagar Thiruvanmiyur, Chennai",9.731865e+09,https://www.justdial.com/Chennai/Sriram-Packer...,"Residential Relocation, All India"
4,NaN,NaN,NaN,NaN,NaN,
5,Jayam Packers and Movers,3.9,"Annai Sathya Nagar 8th Street Nesapakkam, Chennai",8.511079e+09,https://www.justdial.com/Chennai/Jayam-Packers...,"Residential Relocation, Within City"
6,Royal Packers and Movers,3.3,"Sulthan Pettai Mangadu, Chennai",8.511393e+09,https://www.justdial.com/Chennai/Royal-Packers...,"Residential Relocation, Within City"
7,Superline Packers and Movers,4.7,"Near Sathyamoorthy Nagar Vyasarpadi, Chennai",8.123746e+09,https://www.justdial.com/Chennai/Superline-Pac...,"Packers And Movers, Packers And Movers (Within..."
8,Youngers Packers and Movers,4.1,"Ajantha Avenue Kottivakkam, Chennai",9.724736e+09,https://www.justdial.com/Chennai/Youngers-Pack...,"Interstate Moving, Intercity Relocation, Indus..."
9,Nathish Transport,4.3,"Indira Nagar Kolathur, Chennai",8.197736e+09,https://www.justdial.com/Chennai/Nathish-Trans...,"Residential Relocation, All India, Within City"

In [92]:
df["Company_Link"] = (
    "https://" +
    df["Company_Name"].str.upper().str.replace(r"[^A-Z0-9]+", "-", regex=True).str.strip("-")
    + "/"
)

display(df[["Company_Name", "Company_Link"]].head(10))

,Company_Name,Company_Link
0,A 1 Trans Logistic Packers & Movers,https://A-1-TRANS-LOGISTIC-PACKERS-MOVERS/
1,Thangam Packers and Movers,https://THANGAM-PACKERS-AND-MOVERS/
2,Sri Thirumalai Packers Movers and Transports,https://SRI-THIRUMALAI-PACKERS-MOVERS-AND-TRAN...
3,Sriram Packers and Movers,https://SRIRAM-PACKERS-AND-MOVERS/
4,NaN,NaN
5,Jayam Packers and Movers,https://JAYAM-PACKERS-AND-MOVERS/
6,Royal Packers and Movers,https://ROYAL-PACKERS-AND-MOVERS/
7,Superline Packers and Movers,https://SUPERLINE-PACKERS-AND-MOVERS/
8,Youngers Packers and Movers,https://YOUNGERS-PACKERS-AND-MOVERS/
9,Nathish Transport,https://NATHISH-TRANSPORT/

In [93]:
df.head()

,Company_Name,Rating,location,Phone_Number,Website,Amenities,Company_Link
0,A 1 Trans Logistic Packers & Movers,4.0,"Thiruverkadu Road Poonamallee, Chennai",8.147128e+09,https://www.justdial.com/Chennai/A-1-Trans-Log...,"Residential Relocation, Domestic Shifting, All...",https://A-1-TRANS-LOGISTIC-PACKERS-MOVERS/
1,Thangam Packers and Movers,4.4,Sri Ayyappan Nagar 1st Main Road Virugambakkam...,9.740218e+09,https://www.justdial.com/Chennai/Thangam-Packe...,"Budget Friendly, Warehousing, Two Wheeler Tran...",https://THANGAM-PACKERS-AND-MOVERS/
2,Sri Thirumalai Packers Movers and Transports,4.3,"Srinivasapuram Iyyappanthangal, Chennai",8.904958e+09,https://www.justdial.com/Chennai/Sri-Thirumala...,Residential Relocation,https://SRI-THIRUMALAI-PACKERS-MOVERS-AND-TRAN...
3,Sriram Packers and Movers,4.0,"Ptk Nagar Thiruvanmiyur, Chennai",9.731865e+09,https://www.justdial.com/Chennai/Sriram-Packer...,"Residential Relocation, All India",https://SRIRAM-PACKERS-AND-MOVERS/
4,NaN,NaN,NaN,NaN,NaN,,NaN

In [95]:
df.drop(columns=["Website"])

,Company_Name,Rating,location,Phone_Number,Amenities,Company_Link
0,A 1 Trans Logistic Packers & Movers,4.0,"Thiruverkadu Road Poonamallee, Chennai",8.147128e+09,"Residential Relocation, Domestic Shifting, All...",https://A-1-TRANS-LOGISTIC-PACKERS-MOVERS/
1,Thangam Packers and Movers,4.4,Sri Ayyappan Nagar 1st Main Road Virugambakkam...,9.740218e+09,"Budget Friendly, Warehousing, Two Wheeler Tran...",https://THANGAM-PACKERS-AND-MOVERS/
2,Sri Thirumalai Packers Movers and Transports,4.3,"Srinivasapuram Iyyappanthangal, Chennai",8.904958e+09,Residential Relocation,https://SRI-THIRUMALAI-PACKERS-MOVERS-AND-TRAN...
3,Sriram Packers and Movers,4.0,"Ptk Nagar Thiruvanmiyur, Chennai",9.731865e+09,"Residential Relocation, All India",https://SRIRAM-PACKERS-AND-MOVERS/
4,NaN,NaN,NaN,NaN,,NaN
...,...,...,...,...,...,...
176,Southern Logistic Packers and Movers,4.6,"Poonamallee Bypass Road Ambal Nager, Chennai",NaN,Indian Banks Association Approved,https://SOUTHERN-LOGISTIC-PACKERS-AND-MOVERS/
177,Vr Logistics Packers and Movers,4.6,"Balaji Nagar Main Road Puzhal, Chennai",NaN,"Packers And Movers For Bangalore, Packers And ...",https://VR-LOGISTICS-PACKERS-AND-MOVERS/
178,Sri Hari Packers & Movers,3.0,"Bharathi Nagar Thiruvanmiyur, Chennai",NaN,All India,https://SRI-HARI-PACKERS-MOVERS/
179,Papathi Packers and Movers,4.8,"Kalaingar Karunanidhi Nagar K K Nagar, Chennai",NaN,All India,https://PAPATHI-PACKERS-AND-MOVERS/
180,Ashwin Transport & Packers Movers,4.2,"Mohan Nagar-Maadambakkam, Chennai",NaN,"Packers And Movers, Packers And Movers (Within...",https://ASHWIN-TRANSPORT-PACKERS-MOVERS/

In [96]:
df.rename(columns={
    "Company_Link": "Website Link",
    }, inplace=True)

In [97]:
df.head()

,Company_Name,Rating,location,Phone_Number,Website,Amenities,Website Link
0,A 1 Trans Logistic Packers & Movers,4.0,"Thiruverkadu Road Poonamallee, Chennai",8.147128e+09,https://www.justdial.com/Chennai/A-1-Trans-Log...,"Residential Relocation, Domestic Shifting, All...",https://A-1-TRANS-LOGISTIC-PACKERS-MOVERS/
1,Thangam Packers and Movers,4.4,Sri Ayyappan Nagar 1st Main Road Virugambakkam...,9.740218e+09,https://www.justdial.com/Chennai/Thangam-Packe...,"Budget Friendly, Warehousing, Two Wheeler Tran...",https://THANGAM-PACKERS-AND-MOVERS/
2,Sri Thirumalai Packers Movers and Transports,4.3,"Srinivasapuram Iyyappanthangal, Chennai",8.904958e+09,https://www.justdial.com/Chennai/Sri-Thirumala...,Residential Relocation,https://SRI-THIRUMALAI-PACKERS-MOVERS-AND-TRAN...
3,Sriram Packers and Movers,4.0,"Ptk Nagar Thiruvanmiyur, Chennai",9.731865e+09,https://www.justdial.com/Chennai/Sriram-Packer...,"Residential Relocation, All India",https://SRIRAM-PACKERS-AND-MOVERS/
4,NaN,NaN,NaN,NaN,NaN,,NaN

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Company_Name  177 non-null    object
 1   Rating        177 non-null    float64
 2   location      177 non-null    object
 3   Phone_Number  86 non-null     float64
 4   Website       177 non-null    object
 5   Amenities     181 non-null    object
 6   Company_Link  177 non-null    object
dtypes: float64(2), object(5)
memory usage: 10.0+ KB

In [99]:
print(df.columns.to_list())

['Company_Name', 'Rating', 'location', 'Phone_Number', 'Website', 'Amenities', 'Website Link']

In [102]:
import re
import pandas as pd

# ==== Clean Location safely ====
def extract_location(location):
    if pd.isna(location):
        return None

    location = str(location).strip()
    return location if location else None

df["location"] = df["location"].apply(extract_location)

# ==== Clean and standardize ====
df["location"] = (
    df["location"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .str.title()
)

# ==== Group by Location and count records ====
location_counts = (
    df.groupby("location")
    .size()
    .reset_index(name="Total_Records")
)

# ==== Sort by total records (descending) ====
location_counts = location_counts.sort_values(
    by="Total_Records",
    ascending=False
)

# ==== Show result ====
print(location_counts)

                                             location  Total_Records
55                      Nerkundram-Koyambedu, Chennai              5
67                   Ptk Nagar Thiruvanmiyur, Chennai              5
6                      5Th Street Medavakkam, Chennai              4
2                      17Th Street Velacheri, Chennai              2
3                  2Nd Cross Seelanaickenpatti, Salem              2
..                                                ...            ...
70         Sathya Moorthy Street Choolaimedu, Chennai              1
65       Poonamallee Bypass Road Ambal Nager, Chennai              1
82     State Bank Colony Chinnavedampatti, Coimbatore              1
79  Sri Ayyappan Nagar 1St Main Road Virugambakkam...              1
88             Thiruverkadu Road Poonamallee, Chennai              1

[95 rows x 2 columns]

In [104]:
district = input("Enter district: ").strip()

filtered_df = df[
    df["location"].str.split(",").str[-1].str.strip().str.casefold()
    == district.casefold()
]

display(filtered_df)

print("Total records:", len(filtered_df))

Enter district: salem

,Company_Name,Rating,location,Phone_Number,Website,Amenities,Website Link
47,DHUVARAGA TRANSPORT,5.0,"Devangapuram Extension Shevapet, Salem",7.947218e+09,https://www.justdial.com/Salem/DHUVARAGA-TRANS...,"Transporters, Packers And Movers",https://DHUVARAGA-TRANSPORT/
48,SALEM METRO PACKERS & MOVERS,4.5,"Dr Subrayan Street Salem Fort, Salem",7.041691e+09,https://www.justdial.com/Salem/SALEM-METRO-PAC...,"All India, Within City",https://SALEM-METRO-PACKERS-MOVERS/
49,PLACE TO PLACE PACKERS AND MOVERS,5.0,"Murugan Koil Street Fair Lands, Salem",8.050901e+09,https://www.justdial.com/Salem/PLACE-TO-PLACE-...,"Budget Friendly, Intercity Relocation, IT Relo...",https://PLACE-TO-PLACE-PACKERS-AND-MOVERS/
50,Rudhran Packers and Movers,5.0,"2Nd Cross Seelanaickenpatti, Salem",8.460387e+09,https://www.justdial.com/Salem/Rudhran-Packers...,"Loading & Unloading Services, Packers And Movers",https://RUDHRAN-PACKERS-AND-MOVERS/
57,DHUVARAGA TRANSPORT,5.0,"Devangapuram Extension Shevapet, Salem",7.947218e+09,https://www.justdial.com/Salem/DHUVARAGA-TRANS...,"Transporters, Packers And Movers",https://DHUVARAGA-TRANSPORT/
58,SALEM METRO PACKERS & MOVERS,4.5,"Dr Subrayan Street Salem Fort, Salem",7.041691e+09,https://www.justdial.com/Salem/SALEM-METRO-PAC...,"All India, Within City",https://SALEM-METRO-PACKERS-MOVERS/
59,PLACE TO PLACE PACKERS AND MOVERS,5.0,"Murugan Koil Street Fair Lands, Salem",8.050901e+09,https://www.justdial.com/Salem/PLACE-TO-PLACE-...,"Budget Friendly, Intercity Relocation, IT Relo...",https://PLACE-TO-PLACE-PACKERS-AND-MOVERS/
60,Rudhran Packers and Movers,5.0,"2Nd Cross Seelanaickenpatti, Salem",8.460387e+09,https://www.justdial.com/Salem/Rudhran-Packers...,"Loading & Unloading Services, Packers And Movers",https://RUDHRAN-PACKERS-AND-MOVERS/

Total records: 8

In [105]:
import pandas as pd

# Count the last part of each location
last_word_counts = (
    df["location"]
    .dropna()
    .str.rsplit(",", n=1)
    .str[-1]
    .str.strip()
    .str.title()
    .value_counts()
    .reset_index()
)

# Rename the output columns
last_word_counts.columns = ["Last_Location", "Count"]

# Display the result
display(last_word_counts)

   Last_Location  Count
0        Chennai    146
1          Salem      8
2        Tirupur      4
3          Thane      3
4          Theni      2
5        Khammam      2
6    Navi Mumbai      2
7         Mumbai      2
8        Madurai      2
9    Kanyakumari      2
10       Tenkasi      1
11    Coimbatore      1
12    Perambalur      1
13        Nashik      1